Let's convert the raw gpkg file into a useable Parquet. It has many layers: 

UserWarning: More than one layer found in 'WAC_CNA_CommodityAoI_GridsCollationUpdate.gpkg': 'WAC_BelCNAaoiUTM_CoffeeBRA_Tiles' (default), 'WAC_BelCNAaoiUTM_CoffeeHND_Tiles', 'WAC_BelCNAaoiUTM_TimberCMR_Tiles', 'WAC_CNAaoiUTM_RubberTHA_Tiles', 'WAC_GerCNAaoiUTM_Cattle_Tiles', 'WAC_GerCNAaoiUTM_Cocoa_Tiles', 'WAC_GerCNAaoiUTM_Coffee_Tiles', 'WAC_GerCNAaoiUTM_OilPalm_Tiles', 'WAC_GerCNAaoiUTM_Rubber_Tiles', 'WAC_GerCNAaoiUTM_Soy_Tiles', 'WAC_GerCNAaoiUTM_Timber_Tiles', 'WAC_ItaCNAaoiUTM_CoffeeETH_Tile', 'WAC_NldCNAaoiUTM_CocoaGHA_Tile', 'WAC_NldCNAaoiUTM_CocoaLBR_Tiles', 'WAC_NldCNAaoiUTM_TimberPNG_Tile', 'WAC_NldCNAaoiUTM_TimberPNG_Tiles1', 'WAC_RouCNAaoiUTM_TimberROU_Tiles', 'layer_styles'. Specify layer parameter to avoid this warning.

In [3]:
layer = "WAC_GerCNAaoiUTM_OilPalm_Tiles"
gpkg = "WAC_CNA_CommodityAoI_GridsCollationUpdate.gpkg"

import geopandas as gpd

gdf = gpd.read_file(gpkg, layer=layer)

gdf

     com                                           geometry
0   palm  POLYGON ((11262924.88 456288.23, 11302999.897 ...
1   palm  POLYGON ((11262924.88 416119.391, 11302999.897...
2   palm  POLYGON ((11302999.897 416119.391, 11343074.91...
3   palm  POLYGON ((11354465.974 655818.803, 11394540.99...
4   palm  POLYGON ((11354465.974 615544.518, 11394540.99...
5   palm  POLYGON ((11379587.072 333451.03, 11419662.089...
6   palm  POLYGON ((11379587.072 293327.562, 11419662.08...
7   palm  POLYGON ((11419662.089 333451.03, 11459737.106...
8   palm  POLYGON ((11419662.089 293327.562, 11459737.10...
9   palm  POLYGON ((11460330.915 356048.779, 11500405.93...
10  palm  POLYGON ((11485560.69 267479, 11525635.707 267...
11  palm  POLYGON ((13093220.76 615929.74, 13133295.777 ...
12  palm  POLYGON ((13166468.985 630563.632, 13206544.00...
13  palm  POLYGON ((13119696.246 548542.53, 13159771.262...
14  palm  POLYGON ((14803218.012 -194895.69, 14843293.02...

In [1]:
import geopandas as gpd
import pandas as pd

gpkg = "WAC_CNA_CommodityAoI_GridsCollationUpdate.gpkg"
out = "WAC_CNA_CommodityAoI_GridsCollationUpdate_all_layers.parquet"

layers = [
    "WAC_BelCNAaoiUTM_CoffeeBRA_Tiles",
    "WAC_BelCNAaoiUTM_CoffeeHND_Tiles",
    "WAC_BelCNAaoiUTM_TimberCMR_Tiles",
    "WAC_CNAaoiUTM_RubberTHA_Tiles",
    "WAC_GerCNAaoiUTM_Cattle_Tiles",
    "WAC_GerCNAaoiUTM_Cocoa_Tiles",
    "WAC_GerCNAaoiUTM_Coffee_Tiles",
    "WAC_GerCNAaoiUTM_OilPalm_Tiles",
    "WAC_GerCNAaoiUTM_Rubber_Tiles",
    "WAC_GerCNAaoiUTM_Soy_Tiles",
    "WAC_GerCNAaoiUTM_Timber_Tiles",
    "WAC_ItaCNAaoiUTM_CoffeeETH_Tile",
    "WAC_NldCNAaoiUTM_CocoaGHA_Tile",
    "WAC_NldCNAaoiUTM_CocoaLBR_Tiles",
    "WAC_NldCNAaoiUTM_TimberPNG_Tile",
    "WAC_NldCNAaoiUTM_TimberPNG_Tiles1",
    "WAC_RouCNAaoiUTM_TimberROU_Tiles",
]

gdfs = []

for layer in layers:
    print(f"Reading {layer}...")

    gdf = gpd.read_file(gpkg, layer=layer)
    gdf["source_layer"] = layer

    gdfs.append(gdf)

combined = gpd.GeoDataFrame(pd.concat(gdfs, ignore_index=True), crs=gdfs[0].crs)

combined.to_parquet(out, index=False)

print(f"\nSaved {len(combined):,} features to:")
print(out)

Reading WAC_BelCNAaoiUTM_CoffeeBRA_Tiles...
Reading WAC_BelCNAaoiUTM_CoffeeHND_Tiles...
Reading WAC_BelCNAaoiUTM_TimberCMR_Tiles...
Reading WAC_CNAaoiUTM_RubberTHA_Tiles...
Reading WAC_GerCNAaoiUTM_Cattle_Tiles...
Reading WAC_GerCNAaoiUTM_Cocoa_Tiles...
Reading WAC_GerCNAaoiUTM_Coffee_Tiles...
Reading WAC_GerCNAaoiUTM_OilPalm_Tiles...
Reading WAC_GerCNAaoiUTM_Rubber_Tiles...
Reading WAC_GerCNAaoiUTM_Soy_Tiles...
Reading WAC_GerCNAaoiUTM_Timber_Tiles...
Reading WAC_ItaCNAaoiUTM_CoffeeETH_Tile...
Reading WAC_NldCNAaoiUTM_CocoaGHA_Tile...
Reading WAC_NldCNAaoiUTM_CocoaLBR_Tiles...
Reading WAC_NldCNAaoiUTM_TimberPNG_Tile...
Reading WAC_NldCNAaoiUTM_TimberPNG_Tiles1...
Reading WAC_RouCNAaoiUTM_TimberROU_Tiles...

Saved 102 features to:
WAC_CNA_CommodityAoI_GridsCollationUpdate_all_layers.parquet

In [2]:
import geopandas as gpd

gdf = gpd.read_parquet("WAC_CNA_CommodityAoI_GridsCollationUpdate_all_layers.parquet")

gdf

,grid_id,cell_width_m,cell_height_m,cell_area_m2,row_idx,col_idx,geometry,source_layer,com
0,1.0,40000.0,40000.0,1.600000e+09,0.0,1.0,"POLYGON ((-5172860.209 -2126492.899, -5172860....",WAC_BelCNAaoiUTM_CoffeeBRA_Tiles,None
1,2.0,40000.0,40000.0,1.600000e+09,1.0,0.0,"POLYGON ((-5132860.209 -2166492.899, -5132860....",WAC_BelCNAaoiUTM_CoffeeBRA_Tiles,None
2,0.0,40000.0,40000.0,1.600000e+09,0.0,0.0,"POLYGON ((-9693685.661 1664721.344, -9693685.6...",WAC_BelCNAaoiUTM_CoffeeHND_Tiles,None
3,1.0,40000.0,40000.0,1.600000e+09,1.0,0.0,"POLYGON ((-9693685.661 1704721.344, -9693685.6...",WAC_BelCNAaoiUTM_CoffeeHND_Tiles,None
4,0.0,40000.0,40000.0,1.600000e+09,0.0,0.0,"POLYGON ((1337690.22 241729.093, 1337690.22 28...",WAC_BelCNAaoiUTM_TimberCMR_Tiles,None
...,...,...,...,...,...,...,...,...,...
97,13.0,40000.0,40000.0,1.600000e+09,2.0,3.0,"POLYGON ((2786343.862 5606720.58, 2786343.862 ...",WAC_RouCNAaoiUTM_TimberROU_Tiles,None
98,14.0,40000.0,40000.0,1.600000e+09,2.0,4.0,"POLYGON ((2786343.862 5646720.58, 2786343.862 ...",WAC_RouCNAaoiUTM_TimberROU_Tiles,None
99,18.0,40000.0,40000.0,1.600000e+09,3.0,3.0,"POLYGON ((2826343.862 5486720.58, 2826343.862 ...",WAC_RouCNAaoiUTM_TimberROU_Tiles,None
100,19.0,40000.0,40000.0,1.600000e+09,3.0,4.0,"POLYGON ((2826343.862 5526720.58, 2826343.862 ...",WAC_RouCNAaoiUTM_TimberROU_Tiles,None
101,26.0,40000.0,40000.0,1.600000e+09,5.0,1.0,"POLYGON ((2866343.862 5486720.58, 2866343.862 ...",WAC_RouCNAaoiUTM_TimberROU_Tiles,None

In [7]:
gdf[gdf["source_layer"] == "WAC_RouCNAaoiUTM_TimberROU_Tiles"]

,grid_id,cell_width_m,cell_height_m,cell_area_m2,row_idx,col_idx,geometry,source_layer,com
96,6.0,40000.0,40000.0,1.600000e+09,1.0,1.0,"POLYGON ((2746343.862 5646720.58, 2746343.862 ...",WAC_RouCNAaoiUTM_TimberROU_Tiles,None
97,13.0,40000.0,40000.0,1.600000e+09,2.0,3.0,"POLYGON ((2786343.862 5606720.58, 2786343.862 ...",WAC_RouCNAaoiUTM_TimberROU_Tiles,None
98,14.0,40000.0,40000.0,1.600000e+09,2.0,4.0,"POLYGON ((2786343.862 5646720.58, 2786343.862 ...",WAC_RouCNAaoiUTM_TimberROU_Tiles,None
99,18.0,40000.0,40000.0,1.600000e+09,3.0,3.0,"POLYGON ((2826343.862 5486720.58, 2826343.862 ...",WAC_RouCNAaoiUTM_TimberROU_Tiles,None
100,19.0,40000.0,40000.0,1.600000e+09,3.0,4.0,"POLYGON ((2826343.862 5526720.58, 2826343.862 ...",WAC_RouCNAaoiUTM_TimberROU_Tiles,None
101,26.0,40000.0,40000.0,1.600000e+09,5.0,1.0,"POLYGON ((2866343.862 5486720.58, 2866343.862 ...",WAC_RouCNAaoiUTM_TimberROU_Tiles,None

Remove adjacent tiles

In [13]:
import geopandas as gpd

gdf = gpd.read_parquet(
    "WAC_CNA_CommodityAoI_GridsCollationUpdate_all_layers.parquet"
).reset_index(drop=True)

gdf = gdf[gdf.geometry.notna() & ~gdf.geometry.is_empty].copy()
gdf["geometry"] = gdf.geometry.make_valid()
gdf = gdf.explode(index_parts=False).reset_index(drop=True)
gdf = gdf[gdf.geometry.geom_type.isin(["Polygon", "MultiPolygon"])].copy()
gdf = gdf[gdf.geometry.notna() & ~gdf.geometry.is_empty].copy()

tol = 1  # CRS units, probably meters

tmp = gdf[["geometry"]].copy()
tmp["geometry"] = tmp.geometry.buffer(0).buffer(tol)

pairs = gpd.sjoin(tmp, tmp, how="inner", predicate="intersects")
pairs = pairs[pairs.index != pairs["index_right"]]

parent = list(range(len(gdf)))


def find(x):
    while parent[x] != x:
        parent[x] = parent[parent[x]]
        x = parent[x]
    return x


def union(a, b):
    ra, rb = find(a), find(b)
    if ra != rb:
        parent[rb] = ra


for left, right in zip(pairs.index, pairs["index_right"]):
    union(left, right)

gdf["adjacency_group"] = [find(i) for i in range(len(gdf))]

filtered = (
    gdf.sort_index()
    .drop_duplicates("adjacency_group")
    .drop(columns="adjacency_group")
    .reset_index(drop=True)
)

filtered.to_parquet("tiles_one_per_adjacent_group.parquet", index=False)

In [15]:
filtered

,grid_id,cell_width_m,cell_height_m,cell_area_m2,row_idx,col_idx,source_layer,com,geometry
0,1.0,40000.0,40000.0,1.600000e+09,0.0,1.0,WAC_BelCNAaoiUTM_CoffeeBRA_Tiles,None,"POLYGON ((-5172860.209 -2126492.899, -5172860...."
1,0.0,40000.0,40000.0,1.600000e+09,0.0,0.0,WAC_BelCNAaoiUTM_CoffeeHND_Tiles,None,"POLYGON ((-9693685.661 1664721.344, -9693685.6..."
2,0.0,40000.0,40000.0,1.600000e+09,0.0,0.0,WAC_BelCNAaoiUTM_TimberCMR_Tiles,None,"POLYGON ((1337690.22 241729.093, 1337690.22 28..."
3,17.0,40000.0,40000.0,1.600000e+09,2.0,1.0,WAC_BelCNAaoiUTM_TimberCMR_Tiles,None,"POLYGON ((1497690.22 281729.093, 1497690.22 32..."
4,6.0,40000.0,40000.0,1.600000e+09,1.0,1.0,WAC_CNAaoiUTM_RubberTHA_Tiles,None,"POLYGON ((11038595.8 967236.544, 11038595.8 10..."
5,8.0,40000.0,40000.0,1.600000e+09,1.0,3.0,WAC_CNAaoiUTM_RubberTHA_Tiles,None,"POLYGON ((11038595.8 1047236.544, 11038595.8 1..."
6,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cattle_Tiles,cattle,"POLYGON ((-7256188.132 -4113754.884, -7216113...."
7,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cattle_Tiles,cattle,"POLYGON ((-7022877.596 -4454375.623, -6982802...."
8,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cattle_Tiles,cattle,"POLYGON ((-6934695.553 -4434357.824, -6894620...."
9,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cattle_Tiles,cattle,"POLYGON ((-6894620.536 -4535151.65, -6854545.5..."
10,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cattle_Tiles,cattle,"POLYGON ((-6763686.14 -4433240.92, -6723611.12..."
11,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cocoa_Tiles,cocoa,"POLYGON ((-8938446.387 -27376.001, -8898371.37..."
12,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cocoa_Tiles,cocoa,"POLYGON ((-8898371.371 52774.719, -8858296.354..."
13,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cocoa_Tiles,cocoa,"POLYGON ((-282242.783 695347.727, -242167.767 ..."
14,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cocoa_Tiles,cocoa,"POLYGON ((5368334.569 -1524462.42, 5408409.586..."
15,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Coffee_Tiles,coffee,"POLYGON ((-10902122.205 2305527.645, -10862047..."
16,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Coffee_Tiles,coffee,"POLYGON ((-10821972.172 2220279.487, -10781897..."
17,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Coffee_Tiles,coffee,"POLYGON ((-10581522.072 2093113.895, -10541447..."
18,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Coffee_Tiles,coffee,"POLYGON ((-10341071.971 1757762.011, -10300996..."
19,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Coffee_Tiles,coffee,"POLYGON ((-10100621.871 1633262.229, -10060546..."
20,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Coffee_Tiles,coffee,"POLYGON ((4126009.052 -27376.001, 4166084.069 ..."
21,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Coffee_Tiles,coffee,"POLYGON ((11980712.322 1468196.77, 12020787.33..."
22,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((11262924.88 456288.23, 11302999.897 ..."
23,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((11354465.974 655818.803, 11394540.99..."
24,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((11379587.072 333451.03, 11419662.089..."
25,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((11460330.915 356048.779, 11500405.93..."
26,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((11485560.69 267479, 11525635.707 267..."
27,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((13093220.76 615929.74, 13133295.777 ..."
28,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((13166468.985 630563.632, 13206544.00..."
29,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((13119696.246 548542.53, 13159771.262..."
30,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((14803218.012 -194895.69, 14843293.02..."
31,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Rubber_Tiles,rubber,"POLYGON ((8574335.904 978313.234, 8614410.921 ..."
32,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Soy_Tiles,soy,"POLYGON ((-7127886.457 -2598222.321, -7087811...."
33,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Soy_Tiles,soy,"POLYGON ((-7156623.176 -2791204.685, -7116548...."
34,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Timber_Tiles,timber,"POLYGON ((-8056796.02 -4585915.09, -8016721.00..."
35,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Timber_Tiles,timber,"POLYGON ((-6214999.584 -3644106.873, -6174924...."
36,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Timber_Tiles,timber,"POLYGON ((-6161276.333 -3808241.685, -6121201...."
37,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Timber_Tiles,timber,"POLYGON ((12653715.949 -136030.958, 12693790.9..."
38,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Timber_Tiles,timber,"POLYGON ((12786348.485 -328268.904, 12826423.5..."
39,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Timber_Tiles,timber,"POLYGON ((13022662.756 293327.562, 13062737.77..."
40,2.0,40000.0,40000.0,1.600000e+09,0.0,2.0,WAC_ItaCNAaoiUTM_CoffeeETH_Tile,None,"POLYGON ((4085983.12 833168.754, 4085983.12 87..."
41,0.0,40000.0,40000.0,1.600000e+09,0.0,0.0,WAC_NldCNAaoiUTM_CocoaGHA_Tile,None,"POLYGON ((-240402.688 738569.78, -240402.688 7..."
42,0.0,40000.0,40000.0,1.600000e+09,0.0,0.0,WAC_NldCNAaoiUTM_CocoaLBR_Tiles,None,"POLYGON ((-851804.677 648660.518, -851804.677 ..."
43,2.0,40000.0,40000.0,1.600000e+09,1.0,0.0,WAC_NldCNAaoiUTM_TimberPNG_Tile,None,"POLYGON ((16438156.847 -1055813.798, 16438156...."
44,1.0,40000.0,40000.0,1.600000e+09,0.0,1.0,WAC_NldCNAaoiUTM_TimberPNG_Tiles1,None,"POLYGON ((16033256.876 -462642.55, 16033256.87..."
45,6.0,40000.0,40000.0,1.600000e+09,1.0,1.0,WAC_RouCNAaoiUTM_TimberROU_Tiles,None,"POLYGON ((2746343.862 5646720.58, 2746343.862 ..."
46,18.0,40000.0,40000.0,1.600000e+09,3.0,3.0,WAC_RouCNAaoiUTM_TimberROU_Tiles,None,"POLYGON ((2826343.862 5486720.58, 2826343.862 ..."

In [21]:
import geopandas as gpd
from world_agrocommodities.model_stac import get_model_id

gdf = gpd.read_parquet("tiles_one_per_adjacent_group.parquet")

gdf["spatial_extent"] = gdf.geometry.apply(
    lambda x: {
        "west": x.bounds[0],
        "south": x.bounds[1],
        "east": x.bounds[2],
        "north": x.bounds[3],
        "crs": "EPSG:3857",
    }
)

gdf["temporal_extent"] = [["2020-01-01", "2020-12-31"]] * len(gdf)

gdf["id"] = gdf.index.astype(str)

gdf["year"] = "2020"

gdf["crs"] = "EPSG:3857"

gdf["model_id"] = gdf.apply(
    lambda row: get_model_id(row["spatial_extent"], row["temporal_extent"]), axis=1
)

gdf

STAC Item found:
  ID: WorldAgriCommodities_LatinAmerica_v1
No models found for given extent/time.
STAC Item found:
  ID: WorldAgriCommodities_Africa_v1
STAC Item found:
  ID: WorldAgriCommodities_Africa_v1
STAC Item found:
  ID: WorldAgriCommodities_SoutheastAsia_v1
STAC Item found:
  ID: WorldAgriCommodities_SoutheastAsia_v1
STAC Item found:
  ID: WorldAgriCommodities_LatinAmerica_v1
STAC Item found:
  ID: WorldAgriCommodities_LatinAmerica_v1
STAC Item found:
  ID: WorldAgriCommodities_LatinAmerica_v1
STAC Item found:
  ID: WorldAgriCommodities_LatinAmerica_v1
STAC Item found:
  ID: WorldAgriCommodities_LatinAmerica_v1
STAC Item found:
  ID: WorldAgriCommodities_LatinAmerica_v1
STAC Item found:
  ID: WorldAgriCommodities_LatinAmerica_v1
STAC Item found:
  ID: WorldAgriCommodities_Africa_v1
STAC Item found:
  ID: WorldAgriCommodities_Africa_v1
No models found for given extent/time.
No models found for given extent/time.
No models found for given extent/time.
No models found for given extent/time.
No models found for given extent/time.
STAC Item found:
  ID: WorldAgriCommodities_Africa_v1
STAC Item found:
  ID: WorldAgriCommodities_SoutheastAsia_v1
STAC Item found:
  ID: WorldAgriCommodities_SoutheastAsia_v1
STAC Item found:
  ID: WorldAgriCommodities_SoutheastAsia_v1
STAC Item found:
  ID: WorldAgriCommodities_SoutheastAsia_v1
STAC Item found:
  ID: WorldAgriCommodities_SoutheastAsia_v1
STAC Item found:
  ID: WorldAgriCommodities_SoutheastAsia_v1
STAC Item found:
  ID: WorldAgriCommodities_SoutheastAsia_v1
STAC Item found:
  ID: WorldAgriCommodities_SoutheastAsia_v1
STAC Item found:
  ID: WorldAgriCommodities_SoutheastAsia_v1
STAC Item found:
  ID: WorldAgriCommodities_SoutheastAsia_v1
No models found for given extent/time.
STAC Item found:
  ID: WorldAgriCommodities_LatinAmerica_v1
STAC Item found:
  ID: WorldAgriCommodities_LatinAmerica_v1
STAC Item found:
  ID: WorldAgriCommodities_LatinAmerica_v1
STAC Item found:
  ID: WorldAgriCommodities_LatinAmerica_v1
STAC Item found:
  ID: WorldAgriCommodities_LatinAmerica_v1
STAC Item found:
  ID: WorldAgriCommodities_SoutheastAsia_v1
STAC Item found:
  ID: WorldAgriCommodities_SoutheastAsia_v1
STAC Item found:
  ID: WorldAgriCommodities_SoutheastAsia_v1
STAC Item found:
  ID: WorldAgriCommodities_Africa_v1
STAC Item found:
  ID: WorldAgriCommodities_Africa_v1
STAC Item found:
  ID: WorldAgriCommodities_Africa_v1
STAC Item found:
  ID: WorldAgriCommodities_SoutheastAsia_v1
STAC Item found:
  ID: WorldAgriCommodities_SoutheastAsia_v1
No models found for given extent/time.
No models found for given extent/time.

,grid_id,cell_width_m,cell_height_m,cell_area_m2,row_idx,col_idx,source_layer,com,geometry,spatial_extent,temporal_extent,id,year,crs,model_id
0,1.0,40000.0,40000.0,1.600000e+09,0.0,1.0,WAC_BelCNAaoiUTM_CoffeeBRA_Tiles,None,"POLYGON ((-5172860.209 -2126492.899, -5172860....","{'west': -5212860.209308151, 'south': -2126492...","[2020-01-01, 2020-12-31]",0,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
1,0.0,40000.0,40000.0,1.600000e+09,0.0,0.0,WAC_BelCNAaoiUTM_CoffeeHND_Tiles,None,"POLYGON ((-9693685.661 1664721.344, -9693685.6...","{'west': -9733685.660898335, 'south': 1664721....","[2020-01-01, 2020-12-31]",1,2020,EPSG:3857,None
2,0.0,40000.0,40000.0,1.600000e+09,0.0,0.0,WAC_BelCNAaoiUTM_TimberCMR_Tiles,None,"POLYGON ((1337690.22 241729.093, 1337690.22 28...","{'west': 1297690.2200240241, 'south': 241729.0...","[2020-01-01, 2020-12-31]",2,2020,EPSG:3857,WorldAgriCommodities_Africa_v1
3,17.0,40000.0,40000.0,1.600000e+09,2.0,1.0,WAC_BelCNAaoiUTM_TimberCMR_Tiles,None,"POLYGON ((1497690.22 281729.093, 1497690.22 32...","{'west': 1457690.2200240241, 'south': 281729.0...","[2020-01-01, 2020-12-31]",3,2020,EPSG:3857,WorldAgriCommodities_Africa_v1
4,6.0,40000.0,40000.0,1.600000e+09,1.0,1.0,WAC_CNAaoiUTM_RubberTHA_Tiles,None,"POLYGON ((11038595.8 967236.544, 11038595.8 10...","{'west': 10998595.800302817, 'south': 967236.5...","[2020-01-01, 2020-12-31]",4,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
5,8.0,40000.0,40000.0,1.600000e+09,1.0,3.0,WAC_CNAaoiUTM_RubberTHA_Tiles,None,"POLYGON ((11038595.8 1047236.544, 11038595.8 1...","{'west': 10998595.800302817, 'south': 1047236....","[2020-01-01, 2020-12-31]",5,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
6,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cattle_Tiles,cattle,"POLYGON ((-7256188.132 -4113754.884, -7216113....","{'west': -7256188.132125146, 'south': -4162564...","[2020-01-01, 2020-12-31]",6,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
7,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cattle_Tiles,cattle,"POLYGON ((-7022877.596 -4454375.623, -6982802....","{'west': -7022877.596027776, 'south': -4504747...","[2020-01-01, 2020-12-31]",7,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
8,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cattle_Tiles,cattle,"POLYGON ((-6934695.553 -4434357.824, -6894620....","{'west': -6934695.553138507, 'south': -4484634...","[2020-01-01, 2020-12-31]",8,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
9,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cattle_Tiles,cattle,"POLYGON ((-6894620.536 -4535151.65, -6854545.5...","{'west': -6894620.536452928, 'south': -4585915...","[2020-01-01, 2020-12-31]",9,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
10,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cattle_Tiles,cattle,"POLYGON ((-6763686.14 -4433240.92, -6723611.12...","{'west': -6763686.1403720435, 'south': -448351...","[2020-01-01, 2020-12-31]",10,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
11,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cocoa_Tiles,cocoa,"POLYGON ((-8938446.387 -27376.001, -8898371.37...","{'west': -8938446.38741743, 'south': -67452.19...","[2020-01-01, 2020-12-31]",11,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
12,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cocoa_Tiles,cocoa,"POLYGON ((-8898371.371 52774.719, -8858296.354...","{'west': -8898371.370731853, 'south': 12699.10...","[2020-01-01, 2020-12-31]",12,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
13,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cocoa_Tiles,cocoa,"POLYGON ((-282242.783 695347.727, -242167.767 ...","{'west': -282242.7833324785, 'south': 655047.8...","[2020-01-01, 2020-12-31]",13,2020,EPSG:3857,WorldAgriCommodities_Africa_v1
14,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cocoa_Tiles,cocoa,"POLYGON ((5368334.569 -1524462.42, 5408409.586...","{'west': 5368334.569334087, 'south': -1565719....","[2020-01-01, 2020-12-31]",14,2020,EPSG:3857,WorldAgriCommodities_Africa_v1
15,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Coffee_Tiles,coffee,"POLYGON ((-10902122.205 2305527.645, -10862047...","{'west': -10902122.205010777, 'south': 2262855...","[2020-01-01, 2020-12-31]",15,2020,EPSG:3857,None
16,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Coffee_Tiles,coffee,"POLYGON ((-10821972.172 2220279.487, -10781897...","{'west': -10821972.17163962, 'south': 2177798....","[2020-01-01, 2020-12-31]",16,2020,EPSG:3857,None
17,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Coffee_Tiles,coffee,"POLYGON ((-10581522.072 2093113.895, -10541447...","{'west': -10581522.07152615, 'south': 2050905....","[2020-01-01, 2020-12-31]",17,2020,EPSG:3857,None
18,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Coffee_Tiles,coffee,"POLYGON ((-10341071.971 1757762.011, -10300996...","{'west': -10341071.97141268, 'south': 1716191....","[2020-01-01, 2020-12-31]",18,2020,EPSG:3857,None
19,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Coffee_Tiles,coffee,"POLYGON ((-10100621.871 1633262.229, -10060546...","{'west': -10100621.871299205, 'south': 1591899...","[2020-01-01, 2020-12-31]",19,2020,EPSG:3857,None
20,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Coffee_Tiles,coffee,"POLYGON ((4126009.052 -27376.001, 4166084.069 ...","{'west': 4126009.0520811547, 'south': -67452.1...","[2020-01-01, 2020-12-31]",20,2020,EPSG:3857,WorldAgriCommodities_Africa_v1
21,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Coffee_Tiles,coffee,"POLYGON ((11980712.322 1468196.77, 12020787.33...","{'west': 11980712.322454538, 'south': 1427085....","[2020-01-01, 2020-12-31]",21,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
22,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((11262924.88 456288.23, 11302999.897 ...","{'west': 11262924.880087959, 'south': 416119.3...","[2020-01-01, 2020-12-31]",22,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
23,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((11354465.974 655818.803, 11394540.99...","{'west': 11354465.973748514, 'south': 615544.5...","[2020-01-01, 2020-12-31]",23,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
24,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((11379587.072 333451.03, 11419662.089...","{'west': 11379587.07217086, 'south': 293327.56...","[2020-01-01, 2020-12-31]",24,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
25,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((11460330.915 356048.779, 11500405.93...","{'west': 11460330.915204324, 'south': 315918.0...","[2020-01-01, 2020-12-31]",25,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
26,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((11485560.69 267479, 11525635.707 267...","{'west': 11485560.690332267, 'south': 227373.7...","[2020-01-01, 2020-12-31]",26,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
27,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((13093220.76 615929.74, 13133295.777 ...","{'west': 13093220.76019405, 'south': 575679.68...","[2020-01-01, 2020-12-31]",27,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
28,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((13166468.985 630563.632, 13206544.00...","{'west': 13166468.985136023, 'south': 590304.8...","[2020-01-01, 2020-12-31]",28,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
29,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((13119696.246 548542.53, 13159771.262...","{'west': 13119696.245754382, 'south': 508329.8...","[2020-01-01, 2020-12-31]",29,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
30,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((14803218.012 -194895.69, 14843293.02...","{'west': 14803218.011517989, 'south': -234993....","[2020-01-01, 2020-12-31]",30,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
31,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Rubber_Tiles,rubber,"POLYGON ((8574335.904 978313.234, 8614410.921 ...","{'west': 8574335.904180367, 'south': 937785.20...","[2020-01-01, 2020-12-31]",31,2020,EPSG:3857,None
32,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Soy_Tiles,soy,"POLYGON ((-7127886.457 -2598222.321, -7087811....","{'west': -7127886.456745937, 'south': -2641726...","[2020-01-01, 2020-12-31]",32,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
33,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Soy_Tiles,soy,"POLYGON ((-7156623.176 -2791204.685, -7116548....","{'west': -7156623.176027792, 'south': -2835241...","[2020-01-01, 2020-12-31]",33,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
34,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Timber_Tiles,timber,"POLYGON ((-8056796.02 -4585915.09, -8016721.00...","{'west': -8056796.020334706, 'south': -4636928...","[2020-01-01, 2020-12-31]",34,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
35,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Timber_Tiles,timber,"POLYGON ((-6214999.584 -3644106.873, -6174924....","{'west': -6214999.584303095, 'south': -3690991...","[2020-01-01, 2020-12-31]",35,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
36,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Timber_Tiles,timber,"POLYGON ((-6161276.333 -3808241.685, -6121201....","{'west': -6161276.332701251, 'south': -3855769...","[2020-01-01, 2020-12-31]",36,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
37,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Timber_Tiles,timber,"POLYGON ((12653715.949 -136030.958, 12693790.9...","{'west': 12653715.948584363, 'south': -176118....","[2020-01-01, 2020-12-31]",37,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
38,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Timber_Tiles,timber,"POLYGON ((12786348.485 -328268.904, 12826423.5...","{'west': 12786348.48492861, 'south': -368403.7...","[2020-01-01, 2020-12-31]",38,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
39,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Timber_Tiles,timber,"POLYGON ((13022662.756 293327.562, 13062737.77...","{'west': 13022662.75627958, 'south': 253215.69...","[2020-01-01, 2020-12-31]",39,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
40,2.0,40000.0,40000.0,1.600000e+09,0.0,2.0,WAC_ItaCNAaoiUTM_CoffeeETH_Tile,None,"POLYGON ((4085983.12 833168.754, 4085983.12 87...","{'west': 4045983.1195315626, 'south': 833168.7...","[2020-01-01, 2020-12-31]",40,2020,EPSG:3857,WorldAgriCommodities_Africa_v1
41,0.0,40000.0,40000.0,1.600000e+09,0.0,0.0,WAC_NldCNAaoiUTM_CocoaGHA_Tile,None,"POLYGON ((-240402.688 738569.78, -240402.688 7...","{'west': -280402.6878658992, 'south': 738569.7...","[2020-01-01, 2020-12-31]",41,2020,EPSG:3857,WorldAgriCommodities_Africa_v1
42,0.0,40000.0,40000.0,1.600000e+09,0.0,0.0,WAC_NldCNAaoiUTM_CocoaLBR_Tiles,None,"POLYGON ((-851804.677 648660.518, -851804.677 ...","{'west': -891804.6770509289, 'south': 648660.5...","[2020-01-01, 2020-12-31]",42,2020,EPSG:3857,WorldAgriCommodities_Africa_v1
43,2.0,40000.0,40000.0,1.600000e+09,1.0,0.0,WAC_NldCNAaoiUTM_TimberPNG_Tile,None,"POLYGON ((16438156.847 -1055813.798, 16438156....","{'west': 16398156.847213175, 'south': -1055813...","[2020-01-01, 2020-12-31]",43,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
44,1.0,40000.0,40000.0,1.600000e+09,0.0,1.0,WAC_NldCNAaoiUTM_TimberPNG_Tiles1,None,"POLYGON ((16033256.876 -462642.55, 16033256.87...","{'west': 15993256.876402041, 'south': -462642....","[2020-01-01, 2020-12-31]",44,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
45,6.0,40000.0,40000.0,1.600000e+09,1.0,1.0,WAC_RouCNAaoiUTM_TimberROU_Tiles,None,"POLYGON ((2746343.862 5646720.58, 2746343.862 ...","{'west': 2706343.8615350854, 'south': 5646720....","[2020-01-01, 2020-12-31]",45,2020,EPSG:3857,None
46,18.0,40000.0,40000.0,1.600000e+09,3.0,3.0,WAC_RouCNAaoiUTM_TimberROU_Tiles,None,"POLYGON ((2826343.862 5486720.58, 2826343.862 ...","{'west': 2786343.8615350854, 'south': 5486720....","[2020-01-01, 2020-12-31]",46,2020,EPSG:3857,None

In [22]:
gdf["model_id"].iloc[1] = "WorldAgriCommodities_LatinAmerica_v1"

gdf["model_id"].iloc[15] = "WorldAgriCommodities_LatinAmerica_v1"
gdf["model_id"].iloc[16] = "WorldAgriCommodities_LatinAmerica_v1"
gdf["model_id"].iloc[17] = "WorldAgriCommodities_LatinAmerica_v1"
gdf["model_id"].iloc[18] = "WorldAgriCommodities_LatinAmerica_v1"
gdf["model_id"].iloc[19] = "WorldAgriCommodities_LatinAmerica_v1"

gdf["model_id"].iloc[31] = "WorldAgriCommodities_SoutheastAsia_v1"

/tmp/ipykernel_21551/1297605868.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  gdf['model_id'].iloc[1] = 'WorldAgriCommodities_LatinAmerica_v1'
/tmp/ipykernel_21551/1297605868.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gdf['model_id'].iloc[1] = 'WorldAgriCommodities_LatinAmerica_v1'
/tmp/ipykernel_21551/1297605868.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  gdf['model_id'].iloc[15] = 'WorldAgriCommodities_LatinAmerica_v1'
/tmp/ipykernel_21551/1297605868.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gdf['model_id'].iloc[15] = 'WorldAgriCommodities_LatinAmerica_v1'
/tmp/ipykernel_21551/1297605868.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  gdf['model_id'].iloc[16] = 'WorldAgriCommodities_LatinAmerica_v1'
/tmp/ipykernel_21551/1297605868.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gdf['model_id'].iloc[16] = 'WorldAgriCommodities_LatinAmerica_v1'
/tmp/ipykernel_21551/1297605868.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  gdf['model_id'].iloc[17] = 'WorldAgriCommodities_LatinAmerica_v1'
/tmp/ipykernel_21551/1297605868.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gdf['model_id'].iloc[17] = 'WorldAgriCommodities_LatinAmerica_v1'
/tmp/ipykernel_21551/1297605868.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  gdf['model_id'].iloc[18] = 'WorldAgriCommodities_LatinAmerica_v1'
/tmp/ipykernel_21551/1297605868.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gdf['model_id'].iloc[18] = 'WorldAgriCommodities_LatinAmerica_v1'
/tmp/ipykernel_21551/1297605868.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  gdf['model_id'].iloc[19] = 'WorldAgriCommodities_LatinAmerica_v1'
/tmp/ipykernel_21551/1297605868.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gdf['model_id'].iloc[19] = 'WorldAgriCommodities_LatinAmerica_v1'
/tmp/ipykernel_21551/1297605868.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  gdf['model_id'].iloc[31] = 'WorldAgriCommodities_SoutheastAsia_v1'
/tmp/ipykernel_21551/1297605868.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gdf['model_id'].iloc[31] = 'WorldAgriCommodities_SoutheastAsia_v1'

In [25]:
gdf = gdf[gdf["com"] != "timber"].reset_index(drop=True)

# remove index 2,3,37,38,39,40

gdf = gdf.drop(index=[2, 3, 37, 38, 39, 40]).reset_index(drop=True)
gdf

,grid_id,cell_width_m,cell_height_m,cell_area_m2,row_idx,col_idx,source_layer,com,geometry,spatial_extent,temporal_extent,id,year,crs,model_id
0,1.0,40000.0,40000.0,1.600000e+09,0.0,1.0,WAC_BelCNAaoiUTM_CoffeeBRA_Tiles,None,"POLYGON ((-5172860.209 -2126492.899, -5172860....","{'west': -5212860.209308151, 'south': -2126492...","[2020-01-01, 2020-12-31]",0,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
1,0.0,40000.0,40000.0,1.600000e+09,0.0,0.0,WAC_BelCNAaoiUTM_CoffeeHND_Tiles,None,"POLYGON ((-9693685.661 1664721.344, -9693685.6...","{'west': -9733685.660898335, 'south': 1664721....","[2020-01-01, 2020-12-31]",1,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
2,6.0,40000.0,40000.0,1.600000e+09,1.0,1.0,WAC_CNAaoiUTM_RubberTHA_Tiles,None,"POLYGON ((11038595.8 967236.544, 11038595.8 10...","{'west': 10998595.800302817, 'south': 967236.5...","[2020-01-01, 2020-12-31]",4,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
3,8.0,40000.0,40000.0,1.600000e+09,1.0,3.0,WAC_CNAaoiUTM_RubberTHA_Tiles,None,"POLYGON ((11038595.8 1047236.544, 11038595.8 1...","{'west': 10998595.800302817, 'south': 1047236....","[2020-01-01, 2020-12-31]",5,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
4,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cattle_Tiles,cattle,"POLYGON ((-7256188.132 -4113754.884, -7216113....","{'west': -7256188.132125146, 'south': -4162564...","[2020-01-01, 2020-12-31]",6,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
5,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cattle_Tiles,cattle,"POLYGON ((-7022877.596 -4454375.623, -6982802....","{'west': -7022877.596027776, 'south': -4504747...","[2020-01-01, 2020-12-31]",7,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
6,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cattle_Tiles,cattle,"POLYGON ((-6934695.553 -4434357.824, -6894620....","{'west': -6934695.553138507, 'south': -4484634...","[2020-01-01, 2020-12-31]",8,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
7,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cattle_Tiles,cattle,"POLYGON ((-6894620.536 -4535151.65, -6854545.5...","{'west': -6894620.536452928, 'south': -4585915...","[2020-01-01, 2020-12-31]",9,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
8,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cattle_Tiles,cattle,"POLYGON ((-6763686.14 -4433240.92, -6723611.12...","{'west': -6763686.1403720435, 'south': -448351...","[2020-01-01, 2020-12-31]",10,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
9,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cocoa_Tiles,cocoa,"POLYGON ((-8938446.387 -27376.001, -8898371.37...","{'west': -8938446.38741743, 'south': -67452.19...","[2020-01-01, 2020-12-31]",11,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
10,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cocoa_Tiles,cocoa,"POLYGON ((-8898371.371 52774.719, -8858296.354...","{'west': -8898371.370731853, 'south': 12699.10...","[2020-01-01, 2020-12-31]",12,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
11,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cocoa_Tiles,cocoa,"POLYGON ((-282242.783 695347.727, -242167.767 ...","{'west': -282242.7833324785, 'south': 655047.8...","[2020-01-01, 2020-12-31]",13,2020,EPSG:3857,WorldAgriCommodities_Africa_v1
12,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Cocoa_Tiles,cocoa,"POLYGON ((5368334.569 -1524462.42, 5408409.586...","{'west': 5368334.569334087, 'south': -1565719....","[2020-01-01, 2020-12-31]",14,2020,EPSG:3857,WorldAgriCommodities_Africa_v1
13,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Coffee_Tiles,coffee,"POLYGON ((-10902122.205 2305527.645, -10862047...","{'west': -10902122.205010777, 'south': 2262855...","[2020-01-01, 2020-12-31]",15,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
14,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Coffee_Tiles,coffee,"POLYGON ((-10821972.172 2220279.487, -10781897...","{'west': -10821972.17163962, 'south': 2177798....","[2020-01-01, 2020-12-31]",16,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
15,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Coffee_Tiles,coffee,"POLYGON ((-10581522.072 2093113.895, -10541447...","{'west': -10581522.07152615, 'south': 2050905....","[2020-01-01, 2020-12-31]",17,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
16,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Coffee_Tiles,coffee,"POLYGON ((-10341071.971 1757762.011, -10300996...","{'west': -10341071.97141268, 'south': 1716191....","[2020-01-01, 2020-12-31]",18,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
17,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Coffee_Tiles,coffee,"POLYGON ((-10100621.871 1633262.229, -10060546...","{'west': -10100621.871299205, 'south': 1591899...","[2020-01-01, 2020-12-31]",19,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
18,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Coffee_Tiles,coffee,"POLYGON ((4126009.052 -27376.001, 4166084.069 ...","{'west': 4126009.0520811547, 'south': -67452.1...","[2020-01-01, 2020-12-31]",20,2020,EPSG:3857,WorldAgriCommodities_Africa_v1
19,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Coffee_Tiles,coffee,"POLYGON ((11980712.322 1468196.77, 12020787.33...","{'west': 11980712.322454538, 'south': 1427085....","[2020-01-01, 2020-12-31]",21,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
20,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((11262924.88 456288.23, 11302999.897 ...","{'west': 11262924.880087959, 'south': 416119.3...","[2020-01-01, 2020-12-31]",22,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
21,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((11354465.974 655818.803, 11394540.99...","{'west': 11354465.973748514, 'south': 615544.5...","[2020-01-01, 2020-12-31]",23,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
22,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((11379587.072 333451.03, 11419662.089...","{'west': 11379587.07217086, 'south': 293327.56...","[2020-01-01, 2020-12-31]",24,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
23,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((11460330.915 356048.779, 11500405.93...","{'west': 11460330.915204324, 'south': 315918.0...","[2020-01-01, 2020-12-31]",25,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
24,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((11485560.69 267479, 11525635.707 267...","{'west': 11485560.690332267, 'south': 227373.7...","[2020-01-01, 2020-12-31]",26,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
25,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((13093220.76 615929.74, 13133295.777 ...","{'west': 13093220.76019405, 'south': 575679.68...","[2020-01-01, 2020-12-31]",27,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
26,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((13166468.985 630563.632, 13206544.00...","{'west': 13166468.985136023, 'south': 590304.8...","[2020-01-01, 2020-12-31]",28,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
27,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((13119696.246 548542.53, 13159771.262...","{'west': 13119696.245754382, 'south': 508329.8...","[2020-01-01, 2020-12-31]",29,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
28,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_OilPalm_Tiles,palm,"POLYGON ((14803218.012 -194895.69, 14843293.02...","{'west': 14803218.011517989, 'south': -234993....","[2020-01-01, 2020-12-31]",30,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
29,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Rubber_Tiles,rubber,"POLYGON ((8574335.904 978313.234, 8614410.921 ...","{'west': 8574335.904180367, 'south': 937785.20...","[2020-01-01, 2020-12-31]",31,2020,EPSG:3857,WorldAgriCommodities_SoutheastAsia_v1
30,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Soy_Tiles,soy,"POLYGON ((-7127886.457 -2598222.321, -7087811....","{'west': -7127886.456745937, 'south': -2641726...","[2020-01-01, 2020-12-31]",32,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
31,NaN,NaN,NaN,NaN,NaN,NaN,WAC_GerCNAaoiUTM_Soy_Tiles,soy,"POLYGON ((-7156623.176 -2791204.685, -7116548....","{'west': -7156623.176027792, 'south': -2835241...","[2020-01-01, 2020-12-31]",33,2020,EPSG:3857,WorldAgriCommodities_LatinAmerica_v1
32,2.0,40000.0,40000.0,1.600000e+09,0.0,2.0,WAC_ItaCNAaoiUTM_CoffeeETH_Tile,None,"POLYGON ((4085983.12 833168.754, 4085983.12 87...","{'west': 4045983.1195315626, 'south': 833168.7...","[2020-01-01, 2020-12-31]",40,2020,EPSG:3857,WorldAgriCommodities_Africa_v1
33,0.0,40000.0,40000.0,1.600000e+09,0.0,0.0,WAC_NldCNAaoiUTM_CocoaGHA_Tile,None,"POLYGON ((-240402.688 738569.78, -240402.688 7...","{'west': -280402.6878658992, 'south': 738569.7...","[2020-01-01, 2020-12-31]",41,2020,EPSG:3857,WorldAgriCommodities_Africa_v1
34,0.0,40000.0,40000.0,1.600000e+09,0.0,0.0,WAC_NldCNAaoiUTM_CocoaLBR_Tiles,None,"POLYGON ((-851804.677 648660.518, -851804.677 ...","{'west': -891804.6770509289, 'south': 648660.5...","[2020-01-01, 2020-12-31]",42,2020,EPSG:3857,WorldAgriCommodities_Africa_v1

In [26]:
gdf.to_parquet("job_dataframe.parquet", index=False)

In [20]:
world = gpd.read_file(
    "https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_countries.zip"
)

target_crs = gdf.crs if gdf.crs else "EPSG:3857"
world = world.to_crs(target_crs)

joined = gdf[["geometry"]].sjoin(
    world[["NAME", "geometry"]], how="left", predicate="intersects"
)
joined = joined[~joined.index.duplicated(keep="first")]

gdf["country"] = joined["NAME"]

gdf[["geometry", "country"]]

                                             geometry           country
0   POLYGON ((-5172860.209 -2126492.899, -5172860....            Brazil
1   POLYGON ((-9693685.661 1664721.344, -9693685.6...          Honduras
2   POLYGON ((1337690.22 241729.093, 1337690.22 28...             Gabon
3   POLYGON ((1497690.22 281729.093, 1497690.22 32...          Cameroon
4   POLYGON ((11038595.8 967236.544, 11038595.8 10...          Thailand
5   POLYGON ((11038595.8 1047236.544, 11038595.8 1...          Thailand
6   POLYGON ((-7256188.132 -4113754.884, -7216113....         Argentina
7   POLYGON ((-7022877.596 -4454375.623, -6982802....         Argentina
8   POLYGON ((-6934695.553 -4434357.824, -6894620....         Argentina
9   POLYGON ((-6894620.536 -4535151.65, -6854545.5...         Argentina
10  POLYGON ((-6763686.14 -4433240.92, -6723611.12...         Argentina
11  POLYGON ((-8938446.387 -27376.001, -8898371.37...           Ecuador
12  POLYGON ((-8898371.371 52774.719, -8858296.354...           Ecuador
13  POLYGON ((-282242.783 695347.727, -242167.767 ...             Ghana
14  POLYGON ((5368334.569 -1524462.42, 5408409.586...        Madagascar
15  POLYGON ((-10902122.205 2305527.645, -10862047...            Mexico
16  POLYGON ((-10821972.172 2220279.487, -10781897...            Mexico
17  POLYGON ((-10581522.072 2093113.895, -10541447...            Mexico
18  POLYGON ((-10341071.971 1757762.011, -10300996...            Mexico
19  POLYGON ((-10100621.871 1633262.229, -10060546...         Guatemala
20  POLYGON ((4126009.052 -27376.001, 4166084.069 ...             Kenya
21  POLYGON ((11980712.322 1468196.77, 12020787.33...           Vietnam
22  POLYGON ((11262924.88 456288.23, 11302999.897 ...          Malaysia
23  POLYGON ((11354465.974 655818.803, 11394540.99...          Malaysia
24  POLYGON ((11379587.072 333451.03, 11419662.089...          Malaysia
25  POLYGON ((11460330.915 356048.779, 11500405.93...          Malaysia
26  POLYGON ((11485560.69 267479, 11525635.707 267...          Malaysia
27  POLYGON ((13093220.76 615929.74, 13133295.777 ...          Malaysia
28  POLYGON ((13166468.985 630563.632, 13206544.00...          Malaysia
29  POLYGON ((13119696.246 548542.53, 13159771.262...          Malaysia
30  POLYGON ((14803218.012 -194895.69, 14843293.02...         Indonesia
31  POLYGON ((8574335.904 978313.234, 8614410.921 ...             India
32  POLYGON ((-7127886.457 -2598222.321, -7087811....         Argentina
33  POLYGON ((-7156623.176 -2791204.685, -7116548....         Argentina
34  POLYGON ((-8056796.02 -4585915.09, -8016721.00...             Chile
35  POLYGON ((-6214999.584 -3644106.873, -6174924....           Uruguay
36  POLYGON ((-6161276.333 -3808241.685, -6121201....           Uruguay
37  POLYGON ((12653715.949 -136030.958, 12693790.9...         Indonesia
38  POLYGON ((12786348.485 -328268.904, 12826423.5...         Indonesia
39  POLYGON ((13022662.756 293327.562, 13062737.77...         Indonesia
40  POLYGON ((4085983.12 833168.754, 4085983.12 87...          Ethiopia
41  POLYGON ((-240402.688 738569.78, -240402.688 7...             Ghana
42  POLYGON ((-851804.677 648660.518, -851804.677 ...           Liberia
43  POLYGON ((16438156.847 -1055813.798, 16438156....  Papua New Guinea
44  POLYGON ((16033256.876 -462642.55, 16033256.87...  Papua New Guinea
45  POLYGON ((2746343.862 5646720.58, 2746343.862 ...           Romania
46  POLYGON ((2826343.862 5486720.58, 2826343.862 ...           Romania